title: What mad pursuit
description: Notes on chromatin, genomes, and biology.
url: "https://wtrhacker.github.io"
baseurl: ""
lang: en
timezone: America/New_York

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
